### ISSUE TITLE
Windows, Mac, Ubuntu (multiplatform) version

### ISSUE THREAD

**Issue by pm100** [alucardthefish/CodeNowHere#24]
I would like to contribute multiple things to this project. My first contrib is a windows version.

To do this I made a major change. I converted the build system to cmake. This is way more convenient than the autoconf, automake etc.

I fixed a few non portability issues.

I also change how googletest gets run. I followed their instructions for cmake integration - https://google.github.io/googletest/quickstart-cmake.html

It now builds and runs on windows vs2022, ubuntu gcc, and mac clang M1 ( I dont have an intel mac)

Would you like to take a look at the PR

**Comment by alucardthefish** [comment]
Hi @pm100 

I'm glad you want to contribute to this project. I will take a look for sure. Feel free to create the PR.
