### ISSUE TITLE
the overwrite option doesnt overwrite

### ISSUE THREAD

**Issue by pm100** [alucardthefish/CodeNowHere#26]
```
PS C:\work\CodeNowHere> ls -l foo.cpp


    Directory: C:\work\CodeNowHere


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         3/28/2023   8:48 PM           2520 foo.cpp


PS C:\work\CodeNowHere> cnh this foo.cpp
File foo.cpp already exists in this directory. If you continue its content will be replaced
Do you want to continue (Y/n): Y
foo.cpp created!
PS C:\work\CodeNowHere> ls -l foo.cpp


    Directory: C:\work\CodeNowHere


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         3/30/2023   3:10 PM           3360 foo.cpp


PS C:\work\CodeNowHere>

```

you see that the file size just grows

this is becuase the file is opened in append mode.

Its easy to fix, I can do it, but it would be nice to take my other PR first

**Comment by alucardthefish** [comment]
That would be great! Sure let me first have some time to test the former PR. Thank you very much!

**Comment by pm100** [comment]
I note another issue here. The prompt for overwrite is this

`Do you want to continue (Y/n): `

The accepted convention (see https://askubuntu.com/questions/1154676/why-in-any-installation-prompt-y-n-the-y-is-in-uppercase-and-the-n-in-lowe for example) is that the upper case option is what will happen if you just press enter. 

Thats not what happens here. If I press enter without typing a choice nothing happens.

**Comment by alucardthefish** [comment]
Nice, I didn't know about that convention. Something new I learned today. Thank you @pm100 you have been very proactive with the project by finding issues and proposing solutions.
